dist: trusty
language: python
python: 3.5
addons:
  postgresql: "9.5"
  apt:
    packages:
    - slapd
cache:
- pip
- curl
install:
    - curl -O https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
    - tar zxvf go1.6.linux-amd64.tar.gz
    - sudo mv go /usr/local/
    - go get github.com/mozilla-services/autograph
    - psql -c "CREATE DATABASE dbname ENCODING 'UTF8' TEMPLATE template0;" -U postgres
    - psql -c "CREATE USER admin WITH PASSWORD 'pass';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE dbname TO admin;" -U postgres
    - make install
    - make migrate
before_script:
    - python -m http.server 8080 &
    - cp $TRAVIS_BUILD_DIR/app.wsgi $HOME/
    - cd $HOME && KINTO_INI=$TRAVIS_BUILD_DIR/config/kinto.ini pserve $TRAVIS_BUILD_DIR/config/kinto.ini &
    - autograph -c $TRAVIS_BUILD_DIR/.autograph.yml &
script:
    - bash $TRAVIS_BUILD_DIR/smoke-test.sh
