go: 1.6
language: go
addons:
  postgresql: "9.4"
install:
    - sudo apt-get install python-dev python-virtualenv
    - go get github.com/mozilla-services/autograph
    - psql -c "CREATE DATABASE dbname ENCODING 'UTF8' TEMPLATE template0;" -U postgres
    - psql -c "CREATE USER admin WITH PASSWORD 'pass';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE dbname TO admin;" -U postgres
    - make install
    - make migrate
    - .venv/bin/pip install uwsgi
before_script:
    - cd $HOME && UWSGI_VIRTUALENV=$TRAVIS_BUILD_DIR/.venv $TRAVIS_BUILD_DIR/.venv/bin/uwsgi --http :8888 $TRAVIS_BUILD_DIR/config/kinto.ini &
    - autograph -c $TRAVIS_BUILD_DIR/.autograph.yml &
script:
    - bash $TRAVIS_BUILD_DIR/smoke-test.sh
